name: Forge Fork Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

permissions: write-all

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install yarn dependencies
        run: yarn

      - name: Run Forge fork tests
        run: yarn fork-run:local
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          LOCALHOST_RPC_URL: ${{ secrets.LOCALHOST_RPC_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
